import 'package:flutter/material.dart';

const lightTextTheme = TextTheme(
  headlineLarge: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w600,
    fontSize: 57,
    height: 64 / 57,
    letterSpacing: -0.25,
  ),
  headlineMedium: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w600,
    fontSize: 45,
    height: 52 / 45,
    letterSpacing: 0,
  ),
  headlineSmall: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w600,
    fontSize: 36,
    height: 44 / 36,
    letterSpacing: 0,
  ),
  displayLarge: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 32,
    height: 40 / 32,
    letterSpacing: 0,


  ),
  displayMedium: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w600,
    fontSize: 28,
    height: 36 / 28,
    letterSpacing: 0,
  ),
  displaySmall: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 24,
    height: 32 / 24,
    letterSpacing: 0,
  ),
  bodyLarge: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w400,
    fontSize: 16,
    height: 24 / 16,
    letterSpacing: 0.5,
  ),
  bodyMedium: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w400,
    fontSize: 14,
    height: 20 / 14,
    letterSpacing: 0.25,
  ),
  bodySmall: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w400,
    fontSize: 12,
    height: 20 / 14,
    letterSpacing: 0.1,
  ),
  titleLarge: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 22,
    height: 28 / 22,
    letterSpacing: 0,
  ),
  titleMedium: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 16,
    height: 24 / 16,
    letterSpacing: 0.15,
  ),
  titleSmall: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 14,
    height: 24 / 16,
    letterSpacing: 0.15,
  ),
  labelMedium: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 12,
    height: 16 / 11,
    letterSpacing: 0.5,
  ),
  labelSmall: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 11,
    height: 16 / 11,
    letterSpacing: 0.5,
  ),
);
const darkTextTheme = TextTheme(
  headlineLarge: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w600,
    fontSize: 57,
    height: 64 / 57,
    letterSpacing: -0.25,
  ),
  headlineMedium: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w600,
    fontSize: 45,
    height: 52 / 45,
    letterSpacing: 0,
  ),
  headlineSmall: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w600,
    fontSize: 36,
    height: 44 / 36,
    letterSpacing: 0,
  ),
  displayLarge: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 32,
    height: 40 / 32,
    letterSpacing: 0,
  ),
  displayMedium: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 28,
    height: 36 / 28,
    letterSpacing: 0,
  ),
  displaySmall: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 24,
    height: 32 / 24,
    letterSpacing: 0,
  ),
  bodyLarge: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w400,
    fontSize: 16,
    height: 24 / 16,
    letterSpacing: 0.5,
  ),
  bodyMedium: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w400,
    fontSize: 14,
    height: 20 / 14,
    letterSpacing: 0.25,
  ),
  bodySmall: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w400,
    fontSize: 12,
    height: 20 / 14,
    letterSpacing: 0.1,
  ),
  titleLarge: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 22,
    height: 28 / 22,
    letterSpacing: 0,
  ),
  titleMedium: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w600,
    fontSize: 22,
    height: 28 / 22,
    letterSpacing: 0,
  ),
  titleSmall: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 16,
    height: 24 / 16,
    letterSpacing: 0.15,
  ),
  labelLarge: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 14,
    height: 16 / 11,
    letterSpacing: 0.5,
  ),
  labelSmall: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 11,
    height: 16 / 11,
    letterSpacing: 0.5,
  ),
  labelMedium: TextStyle(
    fontFamily: 'Satoshi',
    fontWeight: FontWeight.w500,
    fontSize: 12,
    height: 16 / 11,
    letterSpacing: 0.5,
  ),
);
